import { FormatType } from "../interfaces/Format";

/**
 * Catálogo de formatos hardcodeados.
 * Para agregar un nuevo formato, simplemente se agrega un nuevo objeto a este array.
 */
export const FORMAT_CATALOG: FormatType[] = [
  {
    id: "LEGALIZACION_CUENTAS",
    name: "Legalización de Cuentas",
    description: "Flujo de gastos, viáticos o compras con comprobantes.",
    icon: "receipt_long",
    fields: [
      { name: "nombre", label: "Nombre", type: "text", required: true, placeholder: "Tu nombre" },
      { name: "apellido", label: "Apellido", type: "text", required: true, placeholder: "Tu apellido" },
      { name: "proyecto", label: "Proyecto", type: "text", required: true, placeholder: "Ej: VELEZ TESORO" },
      {
        name: "compras",
        label: "Compras a Legalizar",
        type: "dynamic-group",
        required: true,
        addLabel: "+ Añadir Compra",
        subFields: [
          { name: "fecha_compra", label: "Fecha de Compra", type: "date", required: true },
          { name: "valor", label: "Valor de Compra (COP)", type: "number", required: true, placeholder: "Ej. 150000" },
          { name: "detalle", label: "Detalle", type: "textarea", required: true, placeholder: "Ej: Materiales ferretería" },
          { name: "foto", label: "Foto Comprobante", type: "image", required: false },
        ],
      },
      {
        name: "total_legalizacion",
        label: "Total Legalización",
        type: "calculated-sum",
        required: false,
        calculateSum: "compras.valor",
      },
    ],
  },
  {
    id: "AVANCE_OBRA",
    name: "Avance de Obra",
    description: "Reporte del porcentaje de avance y estado de obra.",
    icon: "engineering",
    fields: [
      { name: "proyecto", label: "Proyecto", type: "text", required: true, placeholder: "Nombre del proyecto" },
      { name: "fecha", label: "Fecha", type: "date", required: true },
      { name: "elaborado_por", label: "Elaborado Por", type: "text", required: true, placeholder: "Nombre completo" },
      { name: "detalle_actividad", label: "Detalle de Actividad", type: "textarea", required: true, placeholder: "Describe la actividad realizada..." },
      { name: "registro_fotografico", label: "Registro Fotográfico", type: "image", required: true },
      { name: "firma", label: "Firma", type: "signature", required: true },
    ],
  },
  {
    id: "ADICIONALES",
    name: "Adicionales",
    description: "Registro de trabajos adicionales fuera del alcance original.",
    icon: "add_circle",
    fields: [
      { name: "proyecto", label: "Proyecto", type: "text", required: true, placeholder: "Nombre del proyecto" },
      { name: "fecha_solicitud", label: "Fecha de Solicitud", type: "date", required: true },
      { name: "nombre_oficial_encargado", label: "Nombre Oficial Encargado", type: "text", required: true, placeholder: "Nombre completo" },
      { name: "actividad_adicional", label: "Actividad Adicional Solicitada", type: "textarea", required: true, placeholder: "Describe la actividad adicional..." },
      { name: "motivo_actividad", label: "Motivo de la Actividad", type: "textarea", required: true, placeholder: "Justificación o motivo" },
      { name: "nombre_quien_autoriza", label: "Nombre de Quien Autoriza", type: "text", required: true, placeholder: "Nombre de quien autoriza" },
      { name: "firma_autoriza", label: "Firma de Quien Autoriza", type: "signature", required: true },
    ],
  },
  {
    id: "ACTA_ENTREGA",
    name: "Acta de Entrega y Pruebas",
    description: "Documento formal de entrega y pruebas de obra finalizada.",
    icon: "assignment_turned_in",
    fields: [
      { name: "proyecto", label: "Proyecto", type: "text", required: true, placeholder: "Nombre del proyecto" },
      { name: "elaborado_por", label: "Elaborado Por", type: "text", required: true, placeholder: "Nombre completo" },
      { name: "fecha_hora_inicio", label: "Fecha y Hora de Inicio", type: "datetime", required: true },
      { name: "psi_inicial", label: "PSI Inicial", type: "number", required: true, placeholder: "0" },
      { name: "foto_manometro_inicial", label: "Foto Manómetro Inicial", type: "image", required: true },
      { name: "fecha_hora_finalizacion", label: "Fecha y Hora de Finalización", type: "datetime", required: true, minDateFromField: "fecha_hora_inicio" },
      { name: "psi_final", label: "PSI Final", type: "number", required: true, placeholder: "0" },
      { name: "foto_manometro_final", label: "Foto Manómetro Final", type: "image", required: true },
      { name: "cantidad_puntos_instalados", label: "Cantidad de Puntos Instalados", type: "number", required: false, placeholder: "0" },
      { name: "adicionales_supresion", label: "Adicionales (Mangueras, Modificaciones...)", type: "textarea", required: false, placeholder: "Describir adicionales de supresión" },
      { name: "cantidad_sensores_instalados", label: "Cantidad de Sensores Instalados", type: "number", required: false, placeholder: "0" },
      { name: "adicionales_deteccion", label: "Adicionales Detección (Modificaciones)", type: "textarea", required: false, placeholder: "Describir adicionales de detección" },
      {
        name: "elementos_instalados_deteccion",
        label: "Elementos Instalados Detección",
        type: "checkbox-group",
        required: false,
        options: ["Panel de control", "Estación manual con sirena", "Módulo"],
      },
      { name: "observaciones", label: "Observaciones", type: "textarea", required: false, placeholder: "Notas adicionales" },
      { name: "recibido_por", label: "Recibido Por", type: "text", required: true, placeholder: "Nombre de quien recibe" },
      { name: "firma_recibido", label: "Firma Recibido", type: "signature", required: true },
    ],
  },
  {
    id: "ACTA_VISITA_MANTENIMIENTO",
    name: "Acta de Visita Mantenimiento",
    description: "Formulario para inspección y mantenimiento del sistema de red contra incendio.",
    icon: "assignment",
    fields: [
      {
        name: "info_general",
        label: "Información General",
        type: "section",
        required: false,
        subFields: [
          { name: "fecha", label: "Fecha", type: "date", required: true },
          { name: "cliente", label: "Cliente", type: "text", required: true, placeholder: "Nombre del cliente" },
          { name: "proyecto_tienda", label: "Proyecto o Tienda", type: "text", required: true, placeholder: "Nombre del proyecto o tienda" },
          { name: "ciudad", label: "Ciudad", type: "text", required: true, placeholder: "Ciudad" },
          { name: "direccion", label: "Dirección", type: "text", required: true, placeholder: "Dirección" },
        ],
      },

      // Inspección visual de alimentación al local
      {
        name: "inspeccion_alimentacion",
        label: "Inspección visual de alimentación al local",
        type: "section",
        required: false,
        subFields: [
          {
            name: "valvula_monitoreada",
            label: "El local cuenta con válvula monitoreada?",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "valvula_monitoreada_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "valvula_monitoreada_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },
          {
            name: "valvula_zona_comun",
            label: "La válvula se encuentra en zona común?",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "valvula_zona_comun_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "valvula_zona_comun_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },
          {
            name: "propietario_responsable_agua",
            label: "El propietario del local es responsable del suministro de agua?",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "propietario_responsable_agua_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "propietario_responsable_agua_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },
          {
            name: "valvula_alimentacion_abierta",
            label: "La válvula de alimentación está abierta?",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "valvula_alimentacion_abierta_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "valvula_alimentacion_abierta_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },
          {
            name: "valvulas_control_accesibles",
            label: "Las válvulas de control son accesibles para inspección y uso en emergencia?",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "valvulas_control_accesibles_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "valvulas_control_accesibles_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },
          {
            name: "local_drenaje",
            label: "El local cuenta con drenaje?",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "local_drenaje_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "local_drenaje_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },
        ],
      },

      // Inspección visual rociadores
      {
        name: "inspeccion_rociadores",
        label: "Inspección visual rociadores",
        type: "section",
        required: false,
        subFields: [
          {
            name: "rociadores_libres_fugas",
            label: "Los rociadores aparecen libres de fugas",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "rociadores_libres_fugas_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "rociadores_libres_fugas_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "rociadores_libres_corrosion",
            label: "Los rociadores aparecen libres de corrosión",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "rociadores_libres_corrosion_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "rociadores_libres_corrosion_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "rociadores_perdida_fluido",
            label: "Los rociadores presentan perdidas de fluido en el elemento sensible",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "rociadores_perdida_fluido_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "rociadores_perdida_fluido_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "rociadores_carga_perjudicial",
            label: "Los rociadores presentan carga que perjudique el desempeño",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "rociadores_carga_perjudicial_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "rociadores_carga_perjudicial_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "rociadores_pintura_no_fabricante",
            label: "Los rociadores aparecen con pintura que no sea aplicada por el fabricante",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "rociadores_pintura_no_fabricante_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "rociadores_pintura_no_fabricante_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "rociadores_posicionados",
            label: "Los rociadores aparecen debidamente posicionados",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "rociadores_posicionados_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "rociadores_posicionados_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "rociadores_espaciados",
            label: "Los rociadores aparecen debidamente espaciados",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "rociadores_espaciados_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "rociadores_espaciados_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "rociadores_tipo_cantidad",
            label: "Qué tipo de rociadores existen en sitio y cuántos",
            type: "textarea",
            required: false,
            placeholder: "Describa el tipo y cantidad...",
          },
        ],
      },

      // Inspección visual de la tubería
      {
        name: "inspeccion_tuberia",
        label: "INSPECCIÓN VISUAL: DE LA TUBERÍA EXPUESTA E INTERNA (si existe novedad aclarar en observaciones si es en la expuesta o interna).",
        type: "section",
        required: false,
        subFields: [
          {
            name: "tuberia_soportes_flojos",
            label: "Los soportes de la tubería están flojos o desprendidos",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "tuberia_soportes_flojos_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "tuberia_soportes_flojos_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "tuberia_danada",
            label: "Existen tuberías dañadas",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "tuberia_danada_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "tuberia_danada_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "tuberia_dispositivos_soporte_danados",
            label: "Hay dispositivos de soporte dañados o no existen",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "tuberia_dispositivos_soporte_danados_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "tuberia_dispositivos_soporte_danados_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "tuberia_soportes_antisismicos",
            label: "Hay soportes antisísmicos",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "tuberia_soportes_antisismicos_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "tuberia_soportes_antisismicos_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "tuberia_libre_fugas",
            label: "La tubería aparece libre de fugas",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "tuberia_libre_fugas_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "tuberia_libre_fugas_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "tuberia_libre_corrosion",
            label: "La tubería aparece libre de corrosión",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "tuberia_libre_corrosion_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "tuberia_libre_corrosion_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "tuberia_libre_cargas_externas",
            label: "La tubería aparece libre de cargas externas",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "tuberia_libre_cargas_externas_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "tuberia_libre_cargas_externas_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "tuberia_libre_filtracion",
            label: "Tubería libre de filtración",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "tuberia_libre_filtracion_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "tuberia_libre_filtracion_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },

          {
            name: "tuberia_alineada",
            label: "La tubería aparece debidamente alineada",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "tuberia_alineada_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "tuberia_alineada_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese la observación...",
          },
        ],
      },

      // Inspección extintores
      {
        name: "inspeccion_extintores",
        label: "Inspección extintores",
        type: "section",
        required: false,
        subFields: [
          { name: "extintores_total", label: "Cuántos extintores existen en total", type: "number", required: true },
          
          { name: "header_tipo_a", label: "Tipo A", type: "header", required: false },
          { name: "ext_a_2lb", label: "2 LB", type: "number", required: true },
          { name: "ext_a_5lb", label: "5 LB", type: "number", required: true },
          { name: "ext_a_10lb", label: "10 LB", type: "number", required: true },
          { name: "ext_a_20lb", label: "20 LB", type: "number", required: true },
          { name: "ext_a_30lb", label: "30 LB", type: "number", required: true },

          { name: "header_tipo_b", label: "Tipo B", type: "header", required: false },
          { name: "ext_b_5lb", label: "5 LB", type: "number", required: true },
          { name: "ext_b_10lb", label: "10 LB", type: "number", required: true },
          { name: "ext_b_15lb", label: "15 LB", type: "number", required: true },
          { name: "ext_b_20lb", label: "20 LB", type: "number", required: true },
          { name: "ext_b_50lb", label: "50 LB", type: "number", required: true },

          { name: "header_multi", label: "Multipropósito", type: "header", required: false },
          { name: "ext_multi_5lb", label: "5 LB", type: "number", required: true },
          { name: "ext_multi_10lb", label: "10 LB", type: "number", required: true },
          { name: "ext_multi_15lb", label: "15 LB", type: "number", required: true },
          { name: "ext_multi_20lb", label: "20 LB", type: "number", required: true },
          { name: "ext_multi_30lb", label: "30 LB", type: "number", required: true },

          { name: "header_otros", label: "Otro tipo de extintores", type: "header", required: false },
          { 
            name: "ext_otros", 
            label: "Detalle (tipo y capacidad)", 
            type: "textarea", 
            required: false,
            placeholder: "Describa otros tipos y sus capacidades..."
          },
          
          { name: "extintores_vencimiento", label: "Fecha de vencimiento de los extintores", type: "date", required: true },
        ],
      },

      // Inspección Detección
      {
        name: "inspeccion_deteccion",
        label: "INSPECCIÓN DETECCIÓN",
        type: "section",
        required: false,
        subFields: [
          {
            name: "deteccion_cuenta_sistema",
            label: "Cuentan con sistema de detección",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "deteccion_cuenta_sistema_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "deteccion_cuenta_sistema_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese el detalle...",
          },

          {
            name: "deteccion_panel_propio",
            label: "Cuentan con panel de control propio",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "deteccion_panel_propio_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "deteccion_panel_propio_obs",
            label: "Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese el detalle...",
          },

          {
            name: "deteccion_voltaje_baterias",
            label: "Voltaje de baterías del panel",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "deteccion_voltaje_baterias_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "deteccion_voltaje_baterias_obs",
            label: "Voltaje / Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese el voltaje u observación...",
          },

          {
            name: "deteccion_cuantos_detectores",
            label: "Cuántos detectores instalados",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "deteccion_cuantos_detectores_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "deteccion_cuantos_detectores_obs",
            label: "Cantidad / Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese cantidad u observación...",
          },

          {
            name: "deteccion_tipo_marca",
            label: "Tipo de detectores y marca",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "deteccion_tipo_marca_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "deteccion_tipo_marca_obs",
            label: "Detalle (tipo/marca)",
            type: "textarea",
            required: false,
            placeholder: "Ingrese tipo, marca u observación...",
          },

          {
            name: "deteccion_estaciones_manuales",
            label: "Tiene estaciones manuales y cuantas",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "deteccion_estaciones_manuales_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "deteccion_estaciones_manuales_obs",
            label: "Cantidad / Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese cantidad u observación...",
          },

          {
            name: "deteccion_luces_estrobo",
            label: "Tiene luces de estrobo y cuántas",
            type: "switch",
            required: true,
            options: ["SI", "NO", "NA"],
          },
          {
            name: "deteccion_luces_estrobo_obs_check",
            label: "Observación",
            type: "checkbox-group",
            required: false,
            options: ["observacion"],
          },
          {
            name: "deteccion_luces_estrobo_obs",
            label: "Cantidad / Detalle de la observación",
            type: "textarea",
            required: false,
            placeholder: "Ingrese cantidad u observación...",
          },
        ],
      },

      // Descripción Final
      {
        name: "seccion_final",
        label: "REPORTE FINAL",
        type: "section",
        required: false,
        subFields: [
          {
            name: "reporte_descripcion_general",
            label: "DESCRIPCIÓN GENERAL DE LA INSPECCIÓN",
            type: "textarea",
            required: false,
            minRows: 5,
            placeholder: "Escriba aquí la descripción detallada...",
          },
          {
            name: "reporte_recomendaciones",
            label: "RECOMENDACIONES",
            type: "textarea",
            required: false,
            minRows: 5,
            placeholder: "Escriba aquí las recomendaciones...",
          },
        ],
      },

      // Sección de Firmas
      {
        name: "seccion_firmas",
        label: "REGISTRO DE FIRMAS",
        type: "section",
        required: false,
        subFields: [
          { name: "header_firma_cliente", label: "FIRMA FUNCIONARIO CLIENTE", type: "header", required: false },
          { name: "firma_cliente_nombre", label: "Nombre", type: "text", required: true },
          { name: "firma_cliente_cedula", label: "Cédula", type: "text", required: true },
          { name: "firma_cliente_cargo", label: "Cargo", type: "text", required: true },
          { name: "firma_cliente_digital", label: "Firma", type: "signature", required: true },

          { name: "header_firma_fastfire", label: "FIRMA FUNCIONARIO FAST FIRE DE COLOMBIA", type: "header", required: false },
          { name: "firma_fastfire_nombre", label: "Nombre", type: "text", required: true },
          { name: "firma_fastfire_cedula", label: "Cédula", type: "text", required: true },
          { name: "firma_fastfire_cargo", label: "Cargo", type: "text", required: true },
          { name: "firma_fastfire_digital", label: "Firma", type: "signature", required: true },
        ],
      },
    ],
  },
];

export const getFormatTypeById = (id: string): FormatType | undefined =>
  FORMAT_CATALOG.find((f) => f.id === id);
